### ISSUE TITLE
Tabs inside cloudformation YML templates

### ISSUE THREAD

**Issue by oscarbc96** [awslabs/aws-cfn-template-flip#87]
I found that AWS Cloudformation service accepts YML templates that contain tab characters at the end of the line. (Which I think this is not the standard of YML that AWS follows https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-formats.html). But this tool correctly flags this as a problem. I shared this using AWS support chat and they told me to create an issue here. 
So shall the tool be updated to support the same behaviour?
(I would be more than happy to check it if that's the case 🙂)

### Example error:
```
Error: while scanning for the next token
found character '\t' that cannot start any token
  in "<unicode string>", line 6, column 10:
          - a
             ^
```
**Version:** `AWS Cloudformation Template Flip, Version 1.2.1`
**Cloudformation Template:** [test.txt](https://github.com/awslabs/aws-cfn-template-flip/files/3905814/test.txt)

**Comment by stilvoid** [comment]
I don't think there's anything to fix here. cfn-flip is using a more restrictive YAML parser than the CloudFormation service. The only downside is that a user may need to fix their template to be more compliant with the YAML spec in order to use cfn-flip but that's no bad thing when you consider that other tooling is also likely to be affacted by the same issues of non-compliance (e.g. cfn-lint, code editors).
